server:
  port: 3355
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7003/eureka/
    fetch-registry: true
    register-with-eureka: true
spring:
   application:
    name: cloud-config-client
